classes: {
  highlight: {
    style: {
      fill: "lightgreen"
    }
  }
}

OEM -> General
OEM -> Body
OEM -> Paint

General: General Assembly {
  Chassis1: "Chassis 1" {
    1st_Shift: "1st Shift"
    2nd_Shift: "2nd Shift"
    1st_Shift.class: highlight
    2nd_Shift.class: highlight
  }
  Chassis2: "Chassis 2" {
    1st_Shift: "1st Shift"
    2nd_Shift: "2nd Shift"
    1st_Shift.class: highlight
    2nd_Shift.class: highlight
  }
  Chassis3: "Chassis 3" {
    1st_Shift: "1st Shift"
    2nd_Shift: "2nd Shift"
    1st_Shift.class: highlight
    2nd_Shift.class: highlight
  }
}

Body: "Body Shop" {
  Z3: {
    1st_Shift: "1st Shift"
    2nd_Shift: "2nd Shift"
    1st_Shift.class: highlight
    2nd_Shift.class: highlight
  }
  EVA Liftgates: {
    1st_Shift: "1st Shift"
    2nd_Shift: "2nd Shift"
    1st_Shift.class: highlight
    2nd_Shift.class: highlight
  }
}

Paint: {
  Sealer South: {
    1st_Shift: "1st Shift"
    2nd_Shift: "2nd Shift"
    1st_Shift.class: highlight
    2nd_Shift.class: highlight
  }
  Polish/Repair: {
    1st_Shift: "1st Shift"
    2nd_Shift: "2nd Shift"
    1st_Shift.class: highlight
    2nd_Shift.class: highlight
  }
}
